# Generated by Django 5.1.3 on 2024-11-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=150, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=150)),
            ],
        ),
    ]
