# Generated by Django 5.1.3 on 2024-11-14 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login_page", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="login_page",
        ),
    ]
