# Generated by Django 5.1.3 on 2024-11-11 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login_page", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Camera",
            new_name="Login",
        ),
    ]
