# Generated by Django 5.1.3 on 2024-12-08 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login_page", "0002_user_is_active_user_is_staff_user_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="user_table",
        ),
    ]
