# Generated by Django 5.1.3 on 2024-11-11 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login_page", "0002_rename_camera_login"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Login",
            new_name="Member",
        ),
    ]
