# Generated by Django 5.1.3 on 2024-11-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_page", "0004_alter_member_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="password",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="id",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
